### ISSUE TITLE
Plugin stops working after I switch decks

### ISSUE THREAD

**Issue by SwaguarTV** [CLJunge/Spawn.HDT.DeckCodeBot#2]
The bot connects just fine and works initially, but as soon as I switch to a different deck it stops responding until I disconnect and reconnect.

**Comment by CLJunge** [comment]
I'll look into that.

**Comment by SwaguarTV** [comment]
Thanks! ^_^

**Comment by CLJunge** [comment]
Hey, i just updated the plugin. Please check if it works now, when you get the chance.

**Comment by SwaguarTV** [comment]
Seems like it's still having the same problem. I'll keep trying it to see if I can find more info on what causes it, because im not sure if it's switching decks or just after a certain amount of time.
